### ISSUE TITLE
User can delete an entry

### ISSUE THREAD

**Issue by FrankBishop** [FrankBishop/code-journal#4]
## 💰 Motivation

If a user decides that they no longer wish to keep an entry, they should be able to delete it.

## 📐 Plan

Allow users to delete an entry from its edit screen.

## 🖼️ Wireframe

![user can delete an entry](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/v2/user-can-delete-an-entry.png)

## ✅ Task List

- [x] Add a click target for deleting an entry to the entry form that only appears if the user is editing an entry.
- [x] Show a confirmation modal when the user clicks the Delete Entry click target.
- [x] Hide the modal if the user clicks Cancel.
- [x] Remove the entry from the data model and the entry's DOM tree from the page if the user clicks Delete.
- [x] Show the Entries list if the user clicks Delete.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
